### ISSUE TITLE
How to get the rmcorr fit for each participant

### ISSUE THREAD

**Issue by linlin0026** [lmarusich/rmcorr#15]
Hello, thank you very much for developing such a helpful tool; 
In the paper, I noticed that in Figure 5B, you mentioned, **_"Rmcorr: observations from the same participant are given the same color, with corresponding lines to show the rmcorr fit for each participant."_**
How to find the rmcorr fit for each participant in the results, as my dataset has data from multiple subjects at multiple consecutive time points? I want to use your method to calculate the correlation between different species **in each subject.**
I appreciate your help. Thanks again.

**Comment by jbakdash** [comment]
Unfortunately, there's no way in rmcorr to find the fit for each participant because it calculates the overall or common within-individual association. It is possible to extract the varying/random intercepts for each participant.  Here's a vignette: http://lmarusich.github.io/rmcorr/articles/FAQ_and_limitations.html#how-to-extract-the-slope-and-its-confidence-interval 

Also, please note rmcorr does not model time. That is, it is a time-independent model. The only partial exception is if time is included as a measure.  

I'm not sure if this addresses your questions. For modeling and comparing differences among participants/subjects, other levels, and/or change over time, multilevel modeling is probably the best way to go. 

Thanks for the compliment :) 

Hope this is helpful. Feel free to follow-up over email: jbakdash@gmail.com

**Comment by linlin0026** [comment]
Thanks for your reply; I read the faq you provided, and I am also clear rmcorr cannot be used to calculate the correlation between two variables across different samples from one subject.
   Then I have a new confusion: if I want to calculate the correlation between two variables in continuous samples from a group of subjects, how can I determine **whether the effect slope between variables is meaningfully varying between the individual or not**?  Should I calculate the correlation between the two variables in each subject and ensure that it is **_all positive or negative_**?
  In Dr Marta Karas's reply, I learnt that rmcorr does not apply to the correlation calculation between two variables with a large variance of residual; but I still confused  about the limit of large variance.
  Thank you very much for your reply!

**Comment by jbakdash** [comment]
Rmcorr uses the best fit fixed/common slope. A single slope estimate for all participants. **tldr**: It sounds like you'll have to use multilevel modeling for your data and research questions.

Multilevel modeling will let you fit random effect/varying slopes by participant.  Different multilevel models can be compared. Also, multilevel models can be visualized using packages such as merTools (https://cran.r-project.org/web/packages/merTools/vignettes/merToolsIntro.html) and sjstats  (http://www.strengejacke.de/sjPlot/articles/plot_marginal_effects.html)
 
The **About** page for rmcorrShiny has links to resources for multilevel modeling: https://lmarusich.shinyapps.io/shiny_rmcorr/
 
Rmcorr is _approximately_ the same as a multilevel model with a fixed slope and random effect intercept. However, meaningfully varying slopes by individual are problematic for rmcorr. Especially in combination with unbalanced data and/or influential data points- nicely demonstrated by Dr. Karas (as you mentioned): https://martakarass.github.io/post/2022-04-27-rmcorr_vs_lmm/ 

Hopefully, this points you in the right direction!

**Comment by linlin0026** [comment]
Thank you for your prompt and detailed response. I have benefited greatly from it, and I will study the direction you have provided and rearrange my analysis process accordingly ：）
